#!/usr/bin/env ruby

require_relative '../lib/verto'

vertofile_path = ENV['VERTOFILE_PATH'] || Pathname.new(Dir.pwd).join('Vertofile').to_s

begin
  Verto::DSL.load_file(vertofile_path) if File.exists?(vertofile_path)

  Verto::MainCommand.start(ARGV)
rescue Verto::ExitError => ex
  Verto.stderr.puts ex.message
  Verto.stderr.puts 'Exiting Verto...'
  exit 1
end
